<?php
/** @var Account $block */

use VladimirPopov\WebForms\Block\Customer\Account;
use VladimirPopov\WebForms\Block\Customer\Account\Results;

/** @var Results $resultsBlock */
$resultsBlock = $block->getChildBlock('webforms.customer.account.results');
$results_html = trim($block->getChildHtml('webforms.customer.account.results'));
?>
<?php if ($resultsBlock->getPermission('view')) { echo $results_html; } ?>

<?php if ($resultsBlock->getPermission('add')) { ?>
    <div id="webforms-customer-account-form"
         class="webforms-customer-account-form" <?php if($results_html && $resultsBlock->getPermission('view')) echo 'style="display:none"'?>>
        <?= $block->getChildHtml('webforms.customer.account.form') ?>
    </div>
<?php } ?>