<?php
/**
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\SocialLoginFree\Block\Buttons $block */ ?>
<?php if ($block->getButtons()) : ?>
    <div class="pslogin-block pslogin-login" data-mage-init='{"pslogin":{}}'>

        <div class="pslogin-spacer pslogin-clearfix">
            <span class="pslogin-title" style="<?= $block->showShortButtons() ? '' : 'display: none;' ?>"><?= $block->escapeHtml(__('Login with your social account')) ?></span>
        </div>

        <div class="pslogin-buttons">
            <ul class="pslogin-clearfix">
            <?php foreach ($block->getButtons() as $button) : ?>
                <li class="pslogin-button <?= $block->escapeHtmlAttr($button->getNetworkCode()) ?> ps-<?= /* @noEscape */ $block->getButtonDesign() ?>"
                    title="<?= $this->escapeHtmlAttr($button->getLoginText()) ?>">
                    <a class="pslogin-button-link pslogin-button-click"
                       rel="nofollow"
                       href="javascript:void(0);"
                       data-href="<?= $block->escapeHtmlAttr($button->getLoginUrl()) ?>"
                       data-open-on-page="<?= /* @noEscape */ $button->shouldOpenOnPage() ?>"
                       data-width="<?= $block->escapeHtmlAttr($button->getModalWidth()) ?>"
                       data-height="<?= $block->escapeHtmlAttr($button->getModalHeight()) ?>" >
                        <span class="pslogin-button-auto">
                            <span class="pslogin-button-icon"></span>
                            <span class="pslogin-button-text"><?= $this->escapeHtml($button->getLoginText()) ?></span>
                        </span>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>

    </div>
    <div style="clear: both;"></div>

    <script>
        if (window.psloginButtons) {
            requirejs(['pslogin']);
        }
    </script>
<?php endif; ?>
