<?php if($comment = $block->getOrdercomment()):?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __('Order Comments') ?></span>
        </div>
        <div class="admin__page-section-content" style="word-wrap: break-word;">
            <?php echo nl2br($block->escapeHtml($comment));?>
        </div>
    </section>
<?php endif; ?>

