<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php
if ($order->getIsVirtual()) : return '';
endif;
?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>', 'trackorder', 'width=800,height=600,resizable=yes,scrollbars=yes')" title="<?= /* @escapeNotVerified */ __('Track Order') ?>"><?= /* @escapeNotVerified */ __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /* @escapeNotVerified */ $_excl ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
            <?php endif; ?>
            <?php if ($order->getShippingMethod() == 'shippingoptions_shippingoptions'): ?>
                <div class="shippingoptions-info">
                    <div class="option-item"><label><strong>Shipping Method:</strong></label><span class="value"><?= $order->getShippingOptionsMethod(); ?></span></div>
                    <div class="option-item"><label><strong>Shipping Service:</strong></label><span class="value"><?= $order->getShippingOptionsService(); ?></span></div>
                    <div class="option-item"><label><strong>Account No:</strong></label><span class="value"><?= $order->getShippingOptionsAccountNumber(); ?></span></div>
                    <div class="option-item"><label><strong>Zip Code:</strong></label><span class="value"><?= $order->getShippingOptionsAccountZipCodes(); ?></span></div>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <?= /* @escapeNotVerified */ __('No shipping information available') ?>
        <?php endif; ?>
        <?php if ($order->getPartialShipment()): ?>
            <div><span><strong>Partial shipment: </strong><?php echo $order->getPartialShipment(); ?></span></div>
        <?php endif; ?>
    </div>
</div>
